services:
  - type: web
    name: chartx
    env: node
    region: oregon
    plan: free
    buildCommand: |
      cd backend && npm install && npm run build
      cd ../frontend && npm install && npm run build
    startCommand: |
      cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: <your-mongodb-connection-url>
